// Flat C exports observed in duser.dll. Unknown ABIs are intentionally not declared.
// Validated dialects: ISO C17/C23/C26 draft and Windissect C20 (C ABI under C++20).
#pragma once
#ifndef DUSER_C_H
#define DUSER_C_H
#if defined(__cplusplus)
#  if __cplusplus < 202002L
#    define WINDISSECT_C20_PROFILE 0
#  else
#    define WINDISSECT_C20_PROFILE 1
#  endif
extern "C" {
#else
#  if defined(__STDC_VERSION__) && __STDC_VERSION__ < 201710L
#    error "Windissect C output requires C17 or newer"
#  endif
#  define WINDISSECT_C20_PROFILE 0
#  define WINDISSECT_C_STANDARD __STDC_VERSION__
#endif

// Export: GadgetTransSettingChanged (ABI unverified)
// Export: GetCachedDWriteRenderTarget (ABI unverified)
// Export: LookupGadgetTicket (ABI unverified)
// Export: GetGadgetAnimation (ABI unverified)
// Export: SetGadgetFocusEx (ABI unverified)
// Export: InvalidateLayeredDescendants (ABI unverified)
// Export: MapGadgetPoints (ABI unverified)
// Export: GetGadgetProperty (ABI unverified)
// Export: GetGadgetStyle (ABI unverified)
// Export: IsStartDelete (ABI unverified)
// Export: GetGadget (ABI unverified)
// Export: ForwardGadgetMessage (ABI unverified)
// Export: SetGadgetRootInfo (ABI unverified)
// Export: SetGadgetFocus (ABI unverified)
// Export: SetGadgetOrder (ABI unverified)
// Export: CreateGadget (ABI unverified)
// Export: GetGadgetFocus (ABI unverified)
// Export: DeleteHandle (ABI unverified)
// Export: CreateAction (ABI unverified)
// Export: AttachWndProcW (ABI unverified)
// Export: GetGadgetRect (ABI unverified)
// Export: GetGadgetRgn (ABI unverified)
// Export: DUserSendEvent (ABI unverified)
// Export: InvalidateGadget (ABI unverified)
// Export: GetGadgetFlags (ABI unverified)
// Export: SetGadgetStyle (ABI unverified)
// Export: FindGadgetFromPoint (ABI unverified)
// Export: SetGadgetMessageFilter (ABI unverified)
// Export: SetGadgetRect (ABI unverified)
// Export: SetGadgetParent (ABI unverified)
// Export: GetGadgetTicket (ABI unverified)
// Export: DUserPostEvent (ABI unverified)
// Export: DUserFlushDeferredMessages (ABI unverified)
// Export: DUserRegisterGuts (ABI unverified)
// Export: DUserRegisterStub (ABI unverified)
// Export: DUserFlushMessages (ABI unverified)
// Export: DUserRegisterSuper (ABI unverified)
// Export: AddLayeredRef (ABI unverified)
// Export: GetGadgetVisual (ABI unverified)
// Export: EnsureGadgetTransInitialized (ABI unverified)
// Export: CacheDWriteRenderTarget (ABI unverified)
// Export: InitGadgets (ABI unverified)
// Export: GetMessageExA (ABI unverified)
// Export: DisableContainerHwnd (ABI unverified)
// Export: SetGadgetBufferInfo (ABI unverified)
// Export: FindStdColor (ABI unverified)
// Export: UtilDrawBlendRect (ABI unverified)
// Export: AddGadgetMessageHandler (ABI unverified)
// Export: SetGadgetProperty (ABI unverified)
// Export: RegisterGadgetMessage (ABI unverified)
// Export: RegisterGadgetProperty (ABI unverified)
// Export: DetachWndProc (ABI unverified)
// Export: SetGadgetFlags (ABI unverified)
// Export: RemoveGadgetProperty (ABI unverified)
// Export: SetWindowResizeFlag (ABI unverified)
// Export: GetGadgetRootInfo (ABI unverified)
// Export: GetGadgetLayerInfo (ABI unverified)
// Export: GetGadgetBufferInfo (ABI unverified)
// Export: DUserStopPVLAnimation (ABI unverified)
// Export: SetHardwareDeviceUsage (ABI unverified)
// Export: SetTransitionVisualProperties (ABI unverified)
// Export: ScheduleGadgetTransitions (ABI unverified)
// Export: ChangeCurrentAnimationScenario (ABI unverified)
// Export: ReleaseLayeredRef (ABI unverified)
// Export: BuildAnimation (ABI unverified)
// Export: GetDUserModule (ABI unverified)
// Export: BuildInterpolation (ABI unverified)
// Export: DllMain (ABI unverified)
// Export: SetMinimumDCompVersion (ABI unverified)
// Export: GetStdColorI (ABI unverified)
// Export: GetStdColorBrushI (ABI unverified)
// Export: GadgetTransCompositionChanged (ABI unverified)
// Export: DestroyPendingDCVisuals (ABI unverified)
// Export: AutoTrace (ABI unverified)
// Export: GetDebug (ABI unverified)
// Export: BeginHideInputPaneAnimation (ABI unverified)
// Export: BeginShowInputPaneAnimation (ABI unverified)
// Export: BuildDropTarget (ABI unverified)
// Export: ClearTopmostVisual (ABI unverified)
// Export: CustomGadgetHitTestQuery (ABI unverified)
// Export: DetachGadgetVisuals (ABI unverified)
// Export: EndInputPaneAnimation (ABI unverified)
// Export: EnsureAnimationsEnabled (ABI unverified)
// Export: GetFinalAnimatingPosition (ABI unverified)
// Export: ReleaseDetachedObjects (ABI unverified)
// Export: RemoveClippingImmunityFromVisual (ABI unverified)
// Export: DUserGetAlphaPRID (ABI unverified)
// Export: DUserGetRectPRID (ABI unverified)
// Export: DUserGetRotatePRID (ABI unverified)
// Export: DUserGetScalePRID (ABI unverified)
// Export: DUserStopAnimation (ABI unverified)
// Export: DUserCastHandle (ABI unverified)
// Export: DUserDeleteGadget (ABI unverified)
// Export: GetStdColorBrushF (ABI unverified)
// Export: GetStdColorF (ABI unverified)
// Export: GetStdColorPenF (ABI unverified)
// Export: UtilDrawOutlineRect (ABI unverified)
// Export: AdjustClipInsideRef (ABI unverified)
// Export: AttachWndProcA (ABI unverified)
// Export: ClearPushedOpacitiesFromGadgetTree (ABI unverified)
// Export: DUserBuildGadget (ABI unverified)
// Export: DUserCastClass (ABI unverified)
// Export: DUserCastDirect (ABI unverified)
// Export: DUserFindClass (ABI unverified)
// Export: DUserGetGutsData (ABI unverified)
// Export: DUserInstanceOf (ABI unverified)
// Export: DUserPostMethod (ABI unverified)
// Export: DUserSendMethod (ABI unverified)
// Export: DrawGadgetTree (ABI unverified)
// Export: EnumGadgets (ABI unverified)
// Export: FindGadgetMessages (ABI unverified)
// Export: FindGadgetTargetingInfo (ABI unverified)
// Export: FireGadgetMessages (ABI unverified)
// Export: FreeGdiDxInteropStagingBuffer (ABI unverified)
// Export: GetActionTimeslice (ABI unverified)
// Export: GetGadgetBitmap (ABI unverified)
// Export: GetGadgetCenterPoint (ABI unverified)
// Export: GetGadgetMessageFilter (ABI unverified)
// Export: GetGadgetRotation (ABI unverified)
// Export: GetGadgetScale (ABI unverified)
// Export: GetGadgetSize (ABI unverified)
// Export: GetMessageExW (ABI unverified)
// Export: GetStdColorName (ABI unverified)
// Export: GetStdColorPenI (ABI unverified)
// Export: GetStdPalette (ABI unverified)
// Export: InitGadgetComponent (ABI unverified)
// Export: IsGadgetParentChainStyle (ABI unverified)
// Export: IsInsideContext (ABI unverified)
// Export: PeekMessageExA (ABI unverified)
// Export: PeekMessageExW (ABI unverified)
// Export: RegisterGadgetMessageString (ABI unverified)
// Export: UnregisterGadgetMessageString (ABI unverified)
// Export: ReleaseMouseCapture (ABI unverified)
// Export: RemoveGadgetMessageHandler (ABI unverified)
// Export: ResetDUserDevice (ABI unverified)
// Export: SetActionTimeslice (ABI unverified)
// Export: SetAtlasingHints (ABI unverified)
// Export: SetGadgetCenterPoint (ABI unverified)
// Export: SetGadgetFillF (ABI unverified)
// Export: SetGadgetFillI (ABI unverified)
// Export: SetGadgetLayerInfo (ABI unverified)
// Export: SetGadgetRotation (ABI unverified)
// Export: SetGadgetScale (ABI unverified)
// Export: SetRestoreCachedLayeredRefFlag (ABI unverified)
// Export: UnregisterGadgetMessage (ABI unverified)
// Export: UnregisterGadgetProperty (ABI unverified)
// Export: UtilBuildFont (ABI unverified)
// Export: UtilGetColor (ABI unverified)
// Export: UtilSetBackground (ABI unverified)
// Export: WaitMessageEx (ABI unverified)

#ifdef __cplusplus
} // extern "C"
#endif
#endif // DUSER_C_H
